server:
  port: 8081
  servlet:
    context-path: /demo
spring:
  thymeleaf:
    cache: false #开发过程中关闭缓存，不然看不到实时页面
    mode: HTML  # 用非严格的 HTML
    encoding: utf-8
    servlet:
      content-type: text/html
